### ISSUE TITLE
Consider adding more targets to travis.yml

### ISSUE THREAD

**Issue by vjoki** [muja/unrar.rs#21]
Since Travis CI seems to have support for Windows targets for Rust, it might be worth trying `msvc` (and `gnu`?) targets.

Other targets that might be worthwhile:
- OS X, though I have no idea how/if unrar works there.
- `musl`, since there seems to be some demand there?

And to keep the build matrix reasonable, it might be a good idea to only build the stable channel for these.

**Comment by muja** [comment]
Yes, it works on OS X, at least from what I can tell, as I'm using it :)

**Comment by muja** [comment]
Closing as I've migrated to GitHub Actions, and added targets for windows, linux and OS X.
