### ISSUE TITLE
Unable to compile, private type in public interface

### ISSUE THREAD

**Issue by Fiveside** [muja/unrar.rs#3]
I'm getting this error when attempting to build `unrar.rs` using the latest stable rust (`1.12.1`).

```
error[E0446]: private type in public interface
   --> src/archive.rs:335:16
    |
335 |     pub flags: EntryFlags,
    |                ^^^^^^^^^^

error: aborting due to previous error
```

**Comment by muja** [comment]
This was caused by a wildcard dependency updating bitflags to an incompatible version. It should be working now.
