### ISSUE TITLE
basic_extract.rs does not compile

### ISSUE THREAD

**Issue by cpowell** [muja/unrar.rs#41]
Hello, novice Rust user here, so I cannot contribute meaningfully or suggest a fix.

I note that basic_extract.rs does not want to compile in Rust 1.73. Running 'cargo c' outputs errors on the three '?' usages. The error that I see is:

the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `std::ops::FromResidual`)

Regards,
Chris

**Comment by cpowell** [comment]
My apologies. With further exploration I've realized that the enclosing function (in this case main() ) must return  Result<(), Box<dyn std::error::Error>>.

As I mentioned, novice Rust user here, so please forgive the bad issue!

**Comment by muja** [comment]
Hi. No worries! In that case, has your issue been fixed or do you still need something?

**Comment by cpowell** [comment]
Thank you, I am closing the issue now.
