### ISSUE TITLE
Can't open rar files with unicode characters in the file name.

### ISSUE THREAD

**Issue by eparmstrong** [muja/unrar.rs#44]
I made a small program to display if a rar file is solid.  It works for most rar files, but not if there is a unicode char in the file name.
Looking with strace the file name is getting truncated just before the unicode char.  Looking with a debugger the filename is being passed correctly to the unrar library as a wideCstring.

This got me thinking about how the library knows how to convert the raw unicode chars to the file name, reminding me about libc's setlocale.

Calling setlocale before opening the rar file works.:
```rust
use libc::setlocale;
use libc_interface::LC_ALL;
use std::ffi::CString;

fn main() {                                                                                                                                                                       
    let locale = CString::new("en_US.utf8").unwrap(); ‣                                                                                                                           
    let ptr = locale.into_raw(); ‣*mut i8                                                                                                                                         
    unsafe {                                                                                                                                                                      
        let _ = setlocale(LC_ALL, ptr);                                                                                                                                           
    }
   //file_password omitted for bug report. 
   let archive = unrar::Archive::with_password(&file,file_password).open_for_processing().unwrap();
   println!("{:?} is solid: {}",file, archive.is_solid());
}
```
It's important to note that "en_US.utf8" comes from my environmental variables.  And the correct value to use for setlocale can vary from system to system and even user to user.

Ideally we use a  std::ffi::OsString and pass that into the unrar library as there is no requirement that a file name matches the local character set.  I have no idea if that's even doable.

**Comment by muja** [comment]
Thank you for opening an issue on this. There was an ancient PR which set the locale which I declined because it's not acceptable for a library to have such a global side effect.
Could you please upload an archive that is affected so I can run some tests against it when I get the chance?

**Comment by eparmstrong** [comment]
[unicodefilename.zip](https://github.com/muja/unrar.rs/files/14057682/unicodefilename.zip)
As github doesn't support uploading rar files, I am uploading it as a zipped rar file.  It's just the "unrar.rs/data/solid.rar" file renamed to "unicodefilename❤️.rar". As a reminder this is an interaction of libc and the filesystem.  In places where the filesystem has a well defined charset then the library should work fine.  It's only under systems like Linux which do not define the charset of the filesystem that we have problems.

I agree that the library should not run setlocale. It's probably best to just document the need to run setlocale on unix like OSs the way the vendor library does.  Being able to pass a std::ffi::OsString in would be best, but the portability problems with that give me a headache.

**Comment by muja** [comment]
I added a testcase with your file since it builds locally for me (Mac OS). Let's see how the build matrix will fare

**Comment by muja** [comment]
BTW according to [this](https://stackoverflow.com/questions/3130407/c-wide-characters-outputting-incorrectly) SO, you can just `setlocale(LC_ALL, "")`.
It seems this is not fixable by the library (without calling `setlocale`), at least I couldn't find anything, so the best way would be to document this behavior and inform users in the readme.

**Comment by ttys3** [comment]
hi @muja , I got this problem too, and fired a PR: https://github.com/muja/unrar.rs/pull/49
