### ISSUE TITLE
Compilation fails on macOS

### ISSUE THREAD

**Issue by dsully** [muja/unrar.rs#47]
```shell
error[E0599]: no method named `std` found for mutable reference `&mut Build` in the current scope
  --> /home/dsully/.cargo/registry/src/index.crates.io-6f17d22bba15001f/unrar_sys-0.3.1/build.rs:63:10
   |
60 | /     cc::Build::new()
61 | |         .cpp(true) // Switch to C++ library compilation.
62 | |         .opt_level(2)
63 | |         .std("c++14")
   | |         -^^^ method not found in `&mut Build`
   | |_________|
```

**Comment by muja** [comment]
Hi there
This is probably because you have an outdated `Cargo.lock`. The method is only available in `cc >= 1.0.83`.
This can be fixed by running `cargo upgrade` I believe, your `cc` version in Carg.lock is `1.0.83`.

However I'll leave this open and implement a solution

**Comment by dsully** [comment]
Hi - I'm not using `cc` directly in my crate.

**Comment by muja** [comment]
Yes but indirectly. Can you try `cargo upgrade`?

**Comment by dsully** [comment]
Yes, that worked. `cargo update` actually.
