### ISSUE TITLE
32 bit program cannot be compiled

### ISSUE THREAD

**Issue by pzokid2** [muja/unrar.rs#52]
I have a program to unzip rar files. I use the unrar library version 0.5.3.
The compilation process does not have any errors with the 64 bit version, but with the 32 bit version I get an error in the linking step. 

Error environment:
 + Windows 10 Pro 22H2 (Windows 10.0.19045 64 bit)
 + Rustc version 1.79.0
 + MSVC: VS2022 (v143)

Error details:
error: linking with `link.exe` failed: exit code: 1120
 |
  = note: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x86\\link.exe" "/NOLOGO" ...........

  = note: libunrar-8a7759e1b2bd7719.rlib(unrar-8a7759e1b2bd7719.unrar.a333f8354859b790-cgu.1.rcgu.o) : error LNK2019: unresolved external symbol _RARCloseArchive referenced in function __ZN69_$LT$unrar..open_archive..Handle$u20$as$u20$core..ops..drop..Drop$GT$4drop17h8d7f2995cfe0705fE
          libunrar-8a7759e1b2bd7719.rlib(unrar-8a7759e1b2bd7719.unrar.a333f8354859b790-cgu.1.rcgu.o) : error LNK2019: unresolved external symbol _RAROpenArchiveEx referenced in function __ZN5unrar12open_archive65OpenArchive$LT$Mode$C$unrar..open_archive..CursorBeforeHeader$GT$3new17h073924787123f07bE
          libunrar-8a7759e1b2bd7719.rlib(unrar-8a7759e1b2bd7719.unrar.a333f8354859b790-cgu.1.rcgu.o) : error LNK2019: unresolved external symbol _RARSetPassword referenced in function __ZN5unrar12open_archive65OpenArchive$LT$Mode$C$unrar..open_archive..CursorBeforeHeader$GT$3new28_$u7b$$u7b$closure$u7d$$u7d$17h8fe6041f837fbb11E
          libunrar-8a7759e1b2bd7719.rlib(unrar-8a7759e1b2bd7719.unrar.a333f8354859b790-cgu.1.rcgu.o) : error LNK2019: unresolved external symbol _RARSetCallback referenced in function __ZN5unrar12open_archive11read_header17h101451b3ea0cdf95E
          libunrar-8a7759e1b2bd7719.rlib(unrar-8a7759e1b2bd7719.unrar.a333f8354859b790-cgu.1.rcgu.o) : error LNK2019: unresolved external symbol _RARReadHeaderEx referenced in function __ZN5unrar12open_archive11read_header17h101451b3ea0cdf95E
          libunrar-8a7759e1b2bd7719.rlib(unrar-8a7759e1b2bd7719.unrar.a333f8354859b790-cgu.1.rcgu.o) : error LNK2019: unresolved external symbol _RARProcessFileW referenced in function __ZN5unrar12open_archive17Internal$LT$M$GT$16process_file_raw17h39ff48e5e7ac927fE
          D:\Code\rust\test_rust\target\i686-pc-windows-msvc\debug\deps\test_rust.exe : fatal error LNK1120: 6 unresolved externals

error: could not compile `test_rust` (bin "test_rust") due to 1 previous error

**Comment by muja** [comment]
Unfortunately I have no experience with 32 bit systems. This is also a simple wrapper around the C/C++ library, I believe the error originates from there. I honestly doubt 32bit is officially supported. Could you explain your motive behind needing 32 bit?

**Comment by pzokid2** [comment]
I am coding for an AV software, so I need to extract rar files on 32 and 64 bit windows platforms to perform virus scanning

**Comment by muja** [comment]
Is it possible to replicate this in a CI environment e.g. Github CI or docker? Otherwise I cannot help you, you'd have to work on this yourself.

As a disclaimer, I don't think I can help you either way, because this seems to be an issue with unrar C/C++ library. Maybe you can write the rarlabs the details of your build environment and maybe they'll help you.

**Comment by pzokid2** [comment]
As you said the library is built based on unrar C library. I tried compiling unrar lib 32 bit and it worked, it seems this is not rarlab's fault.

Thank you anyway, I will find another way, I am new to rust so I can't fix this error, but there is another approach is LoadLibrary unrar.dll of ralab and call the decompression functions.

**Comment by muja** [comment]
Is there any improvement in using the latest version?
Unfortunately AFAIK 32-bit systems are not really used anymore, so I don't think it's worth it to spend too much time on this. I am happy to accept contributions though, so if you find a fix, feel free to shoot a PR
