### ISSUE TITLE
License of embedded unrar library should be mentioned

### ISSUE THREAD

**Issue by jannic** [muja/unrar.rs#6]
Cargo.toml and unrar_sys/Cargo.toml simply specify the license as "MIT".
This may be true for the rust parts, but the embedded C++ library at unrar_sys/vendor/unrar/
has its own license, which has some restrictions.

The license is available in https://github.com/muja/unrar.rs/blob/master/unrar_sys/vendor/unrar/license.txt but this is virtually invisible to users of the crate.

Please mention this license more prominently.

**Comment by muja** [comment]
Thanks for bringing that up. Do you have an idea where to mention it? In the project readme would be my first though.

**Comment by jannic** [comment]
IMHO it would be best if it could be mentioned in Cargo.toml, so correct license information is displayed on crates.io. But the unrar license is not in https://spdx.org/licenses/ and crates.io seems to verify that a license listed in `license = "..."` is known at SPDX.
Perhaps `license-file = "..."` could be used, but http://doc.crates.io/manifest.html doesn't mention if that's allowed in addition to the `license` key.

So just mentioning the license in the readme file could be a valid compromise. IANAL, but as far as I understand the unrar license, that could be sufficient to comply to the license terms. Mentioning that the software "cannot be used to develop RAR (WinRAR) compatible archiver and to re-create RAR compression algorithm" seems to be important.
