### ISSUE TITLE
Extremely slow for large archives 

### ISSUE THREAD

**Issue by AntoniosBarotsis** [muja/unrar.rs#61]
As the title mentions, when I try to decompress a large archive (~11gb, 800k+ files according to win file explorer) it takes *a lot* of time, after letting it run for just under an hour, I cancelled it. In contrast, the `unrar` binary that comes with an installation of WinRAR took 12 minutes for the same archive. Considering this crate is a wrapper, I should be able to get nearly identical performance in both cases. Note that this was ran in release as well as the following profile:

```toml
[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true
```

It is very possible that the code I used is wildly suboptimal, I can't tell.

This is coming from https://github.com/ouch-org/ouch/issues/714 after I did my own testing and arrived at the numbers I mentioned above. You can find the code [here](https://github.com/AntoniosBarotsis/unrar-test/blob/master/src/main.rs). It reads in a `test.rar` archive and extracts all files to a `test` directory while keeping track of the amount of files extracted.

**Comment by muja** [comment]
I've tried with the [linux](https://github.com/torvalds/linux) codebase, it's ~2 GiB (528MiB packed) with ~100k files. Extracting that rar file with the library takes over a minute for me. Extracting with `rar x` takes 6 seconds. I've tried different methods, both the `basic_extract` example and the more low-level `unrar_sys/examples/lister.rs` which does nothing but call the FFI. There were multiple suspects on my list but I've ruled them all out, even when not extracting at all and just calling `test` on every single entry it takes 60 seconds.

This is obviously unacceptable but also impossible to fix from my side. Maybe there is a regression with a recent version, so my next approach would be to checkout older versions and see if they yield the same results.

After that, not much I can do except mail the DLL authors or RIIR^TM, but this is just a fun side project which hasn't even any use for me anymore, so investing too much time is not really an option.

I'll report back

**Comment by muja** [comment]
I found out why `unrar x` is so fast: it uses multithreading (11 threads). Unfortunately the library does not provide any parameters for multithreaded extraction, so one must open multiple Archive objects in parallel and split the work among threads. With this very naive implementation I was able to bring the time for the `linux.rar` from 60+ seconds down to 10-15 seconds:

```rust
const NUM_THREADS: u32 = 32;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args = std::env::args();
    let file = args.skip(1).next().unwrap_or("archive.rar".to_owned());
    let mut handles = Vec::with_capacity(NUM_THREADS as usize);
    for i in 0..NUM_THREADS {
        let file = file.clone();
        let handle = std::thread::spawn(move || {
            let mut archive = unrar::Archive::new(&file).open_for_processing()?;
            while let Some(header) = archive.read_header()? {
                if header.entry().file_crc % NUM_THREADS == i {
                    archive = header.extract()?;
                } else {
                    archive = header.skip()?;
                }
            }
            anyhow::Ok(())
        });
        handles.push(handle);
    }
    for handle in handles {
        handle.join().unwrap()?;
    }
    Ok(())
}

```

This would have to be done at the application level. It's a bit harder to design a concept for this in the library.

**Comment by AntoniosBarotsis** [comment]
Nice!

I'm confused with the fact that the library doesn't allow for multithreading though, doesn't the `unrar` binary use that library? How does that do multithreading?

**Comment by muja** [comment]
> Nice!
> 
> I'm confused with the fact that the library doesn't allow for multithreading though, doesn't the `unrar` binary use that library? How does that do multithreading?

The binary doesn't use the (extern C) DLL functions that we have to use, it directly interacts with the C++ objects so I'm assuming it can do more there, even though I haven't looked at exactly how it achieves multithreading.

**Comment by muja** [comment]
@AntoniosBarotsis is there anything you feel has to be done on the library side? Otherwise we can close this, right?

**Comment by AntoniosBarotsis** [comment]
I haven't had the time to properly look into this but I guess not. Though keeping it open for anyone that stumbles on the same issue is also an option, up to you

**Comment by ttys3** [comment]
I do not think WinRAR support multi thread extraction.

it only support multi thread compression.

```shell
./rar  | grep threads
  mt<threads>   Set the number of threads
```

rar is for both compress and decompress, so it has `mt` switch

```shell
./unrar  | grep threads
```

unrar does not

see also 
see https://www.reddit.com/r/software/comments/hgf6s/winrar_only_uses_10_of_my_6core_cpu_when/

**Comment by muja** [comment]
@ttys3 thanks for investigating. Either way, unrar uses multiple threads even if it not advertised. To verify this, I had manually compiled unrar with print statements, and for example here, it is setting this value to 11:

https://github.com/muja/unrar.rs/blob/master/unrar_sys/vendor/unrar/cmddata.cpp#L689

**Comment by ttys3** [comment]
> @ttys3 thanks for investigating. Either way, unrar uses multiple threads even if it not advertised. To verify this, I had manually compiled unrar with print statements, and for example here, it is setting this value to 11:
> 
> [`master`/unrar_sys/vendor/unrar/cmddata.cpp#L689](https://github.com/muja/unrar.rs/blob/master/unrar_sys/vendor/unrar/cmddata.cpp?rgh-link-date=2024-12-02T13%3A41%3A10Z#L689)

thansk, that's very helpful.

but I see `define("RAR_SMP", None)`  https://github.com/muja/unrar.rs/blob/1d9e4133b9de7f2402c37d7d41a3564a8008eddc/unrar_sys/build.rs#L83

**Comment by muja** [comment]
`.define("RAR_SMP", None)` enables `RAR_SMP` flag (it is similar to passing `-DRAR_SMP` in `c++/gcc`, just without a value, that's why the `None`), although I don't remember what specifically the `RAR_SMP` does for libraries, but it does not seem to operate in a multithreaded way.

**Comment by ttys3** [comment]
> `.define("RAR_SMP", None)` enables `RAR_SMP` flag (it is similar to passing `-DRAR_SMP` in `c++/gcc`, just without a value, that's why the `None`), although I don't remember what specifically the `RAR_SMP` does for libraries, but it does not seem to operate in a multithreaded way.

Oops, my bad. I did not check the doc of `define`,  I just thought in my head that define `None` should means disabled.

it only enable multi thread when `RAR_SMP` is defined: 

https://github.com/muja/unrar.rs/blob/85e2ed8aefdc127d3ad1f2b0475e2f5b3ad28ee3/unrar_sys/vendor/unrar/cmddata.cpp#L687C1-L696C7
