### ISSUE TITLE
How to Extract a File from a RAR Archive

### ISSUE THREAD

**Issue by tsfTSF7** [muja/unrar.rs#62]
How to Extract a File from a RAR Archive

**Comment by muja** [comment]
What are you struggling with? That's covered in the examples and in the readme, very short usage example:

`Archive::new(filename).open_for_processing()?.read_header()?.extract()?`

**Comment by tsfTSF7** [comment]
Hello ,thanks for replying me !
Archive::new(filename).open_for_processing()?.read_header()?.read()? This is my code,but this only reads the content of the first file in the RAR archive.
I want to read specified&nbsp; file of the RAR archive and I have tried many times and failed.
This is my code for reading specified&nbsp; files of the RAR archive but this code is incorrect.

fn first_file_content1<P: AsRef<Path&gt;&gt;(path: P, target_filename: &amp;str) -&gt; UnrarResult<Vec<u8&gt;&gt; {

    let mut archive = unrar::Archive::new(&amp;path).open_for_processing()?;



    loop {

      let header = archive.read_header()?;



      if header.is_none() {

        return Err(UnrarError::from(unrar::error::Code::EndArchive,unrar::error::When::Read)); 

      }

      let header = header.expect("empty archive");

      if header.entry().filename.to_str().unwrap() == target_filename {

        let (data, _rest) = header.read()?; // Read the entry data

        return Ok(data);

      }

      let _ = header.read(); // Discard data of the current entry

    }

  }

Can you help me and give me some suggestions ? Thank you very much.

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "muja/unrar.rs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月6日(星期天) 中午1:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [muja/unrar.rs] How to Extract a File from a RAR Archive (Issue #62)





 
What are you struggling with? That's covered in the examples and in the readme, very short usage example:
 
Archive::new(filename).open_for_processing()?.read_header()?.extract()?

**Comment by tsfTSF7** [comment]
Archive::new(filename).open_for_processing()?.read_header()?.extract()? 


> What are you struggling with? That's covered in the examples and in the readme, very short usage example:
> 
> `Archive::new(filename).open_for_processing()?.read_header()?.extract()?`

This method doesn't work; the result type is the same as Archive::new(&path).open_for_processing()?, which is a step back.

**Comment by muja** [comment]
No, it is a step forward. Your loop is the correct approach, but you are not looping over anything. If you replace this line it should work:

let _ = header.read(); // Discard data of the current entry

instead:

archive = header.skip(); // Discard data of the current entry

(Note using `skip` here is much more performant because `read` will unpack the file then discard it)

the next iteration in the loop should will do the same until the archive is done

**Comment by tsfTSF7** [comment]
> No, it is a step forward. Your loop is the correct approach, but you are not looping over anything. If you replace this line it should work:
> 
> let _ = header.read(); // Discard data of the current entry
> 
> instead:
> 
> archive = header.skip(); // Discard data of the current entry
> 
> (Note using `skip` here is much more performant because `read` will unpack the file then discard it)
> 
> the next iteration in the loop should will do the same until the archive is done which is when the `read_header` will return `None` which in your case is dealt with as an error. However it doesn’t mean the archive was necessarily empty (unless it’s for the first call) but that there are no more entries and in your case the filename didn’t exist inside the archive

Thank you very much. Your response has been very enlightening, and I have solved my problem. Your patient answers have greatly encouraged me, and I am very excited. I am also willing to pass on this sense of inspiration.

**Comment by muja** [comment]
Glad to hear I was able to help. If you run into any other problems, feel free to contact me. You can start a discussion for more informal questions. Happy coding!
