### ISSUE TITLE
Got EOpen error when debug with gdb 

### ISSUE THREAD

**Issue by sbant** [muja/unrar.rs#7]
same executable, when run normally, it run without problem.

But when debug in Eclipse with gdb, unrar.rs always got EOpen error.

Could you give some advise?

**Comment by sbant** [comment]
I changed src/archive.rs

line 200:
```
        let mut data = native::OpenArchiveData::new(cstr!(filename).as_ptr() as *const _,
                                                                              mode as u32);
```
to:
```
        let filename_cstring = cstr!(filename);
        let mut data = native::OpenArchiveData::new(filename_cstring.as_ptr() as *const _,
                                                    mode as u32);
```

Now, the executable run without problem both in console and debug with gdb in eclipse.

Maybe the problem is: cstr!(filename).as_ptr(), will get a dangling pointer, I'm not sure.

I found there are three location have the usage, as_ptr() as *const _ .

**Comment by muja** [comment]
I had this issue too with gdb. I also don't quite understand the cause, but maybe we should consider that solution

**Comment by vjoki** [comment]
This is indeed a dangling pointer that gets used after free.

The string gets dropped right after `.as_ptr()` because it's not bound to any variable.
