### ISSUE TITLE
Feature request, extract part files in an archive, and extract not overwrite file already on disk

### ISSUE THREAD

**Issue by sbant** [muja/unrar.rs#8]
Current, unrar.rs extract all files in an archive and overwrite files in target directory.

May be add a function:
`fn extract_some_to(self, path: String, file_list: &[str]) -> UnrarResult<OpenArchive>`
to let user extract some file in the archive.

And add at least some notification to user when a file in target directory already exists.

**Comment by muja** [comment]
You are correct, that is something this library shouldn't do. As a prerequisite for this, I would like to make an `Archive` iterable over each `Entry`. However, when trying to do that, it didn't work because of lifetime issues... I'll try to dig in once I have time

**Comment by muja** [comment]
This is possible now with version 0.5, please refer to the docs, but you can choose individually for each file what to do, whether to `extract()` (CWD) , `extract_to(filename)` or `extract_with_base(dirname)` (which will extract the file under that directory.
